//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sauemk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etkinlik
    {
        public int Id { get; set; }
        public string Adi { get; set; }
        public Nullable<System.DateTime> Tarihi { get; set; }
        public Nullable<System.DateTime> AcilisTarihi { get; set; }
        public Nullable<System.DateTime> KapanisTarihi { get; set; }
        public string Aciklama { get; set; }
        public string FotoName { get; set; }
    }
}
